# Generated by Django 3.2.4 on 2021-06-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210620_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(default='', verbose_name='文章内容'),
        ),
    ]
